check for libtool properly
git-svn-id: https://svn.remlab.net/svn/miredo/trunk@699 6046fb1f-dae2-0310-8472-869a43925389

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -67,11 +67,16 @@ exit 1
 echo "Generating \`config.h.in' with autoheader ..."
 autoheader || exit 1
 echo "Installing libtool with libtoolize ..."
-libtoolize --force || exit 1
+libtoolize --force || {
+echo "Error: libtool is probably not on your system, or it is too old."
+echo "You need GNU libtool to rebuild this package."
+exit 1
+}
 echo "Generating \`Makefile.in' with automake ..."
 automake --add-missing || {
 echo "Error: automake is probably not on your system, or it is too old."
 echo "You need GNU automake 1.7 higher to rebuild this package."
+exit 1
 }
 echo "Generating \`configure' script with autoconf ..."
 autoconf || exit 1
